# Reverse proxy https://www.google-analytics.com/r/collect? in particular so that we can change the url and
# bypass the easylist filter that targets "r/collects?".
[[redirects]]
from = "https://analytics-bypassing-adblockers.netlify.com/proxy-colect*"
to = "https://www.google-analytics.com/r/collect:splat"
status = 200
headers = {Access-Control-Allow-Origin = "https://analytics-bypassing-adblockers.netlify.com"}

# Reverse proxy anything after "/proxy/".
[[redirects]]
from = "https://analytics-bypassing-adblockers.netlify.com/proxy/*"
to = ":splat"
status = 200
headers = {Access-Control-Allow-Origin = "https://analytics-bypassing-adblockers.netlify.com"}
